[package]
name = "rust_ind8"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
rusqlite = "0.28"
csv = "1.1"
clap = { version = "4.1", features = ["derive"] }
rustc-serialize = "^0.3"
sys-info = "0.7.0"